/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.cGeneral;

/**
 *
 * @author gmarl
 */
public class General extends javax.swing.JFrame {

    private String usuarioCorreo;
    /**
     * Creates new form General
     */
    public General() {
        this.usuarioCorreo = usuarioCorreo;
        initComponents();
        new cGeneral(this, usuarioCorreo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAsistencia = new javax.swing.JButton();
        btnDepartamento = new javax.swing.JButton();
        iconUsu = new javax.swing.JLabel();
        btnTurno = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        lblUsuarioTipo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAsistencia.setBackground(new java.awt.Color(153, 153, 153));
        btnAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/asistencia.png"))); // NOI18N
        btnAsistencia.setText("Asistencia");
        jPanel1.add(btnAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 180, -1));

        btnDepartamento.setBackground(new java.awt.Color(153, 153, 153));
        btnDepartamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/departamento.png"))); // NOI18N
        btnDepartamento.setText("Departamento");
        jPanel1.add(btnDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 169, 180, -1));

        iconUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/conectado.png"))); // NOI18N
        jPanel1.add(iconUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, -1, -1));

        btnTurno.setBackground(new java.awt.Color(153, 153, 153));
        btnTurno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/turno.png"))); // NOI18N
        btnTurno.setText("Turno");
        jPanel1.add(btnTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 254, 180, 56));

        btnRegistro.setBackground(new java.awt.Color(153, 153, 153));
        btnRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/registroo.png"))); // NOI18N
        btnRegistro.setText("Registro");
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, 180, 53));

        btnEmpleado.setBackground(new java.awt.Color(153, 153, 153));
        btnEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/empleado.png"))); // NOI18N
        btnEmpleado.setText("Empleado");
        jPanel1.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 393, 180, -1));

        lblUsuarioTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuarioTipo.setText("USUARIO");
        jPanel1.add(lblUsuarioTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 81, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(153, 153, 153));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Salir.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 475, 180, 52));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 600));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ediCaballo.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new General().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAsistencia;
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnDepartamento;
    public javax.swing.JButton btnEmpleado;
    public javax.swing.JButton btnRegistro;
    public javax.swing.JButton btnTurno;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconUsu;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblUsuarioTipo;
    // End of variables declaration//GEN-END:variables
}
