package Vista;

import Controlador.cLogin;


public class Login extends javax.swing.JFrame {
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        new cLogin(this);
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        Contraseña = new javax.swing.JPasswordField();
        txtCorreoElec = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        mtrContraseña = new javax.swing.JCheckBox();
        lblCorreoElec = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        diseñoCorreoElec = new javax.swing.JLabel();
        diseñoContraseña = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        barraRegistro = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiRegistrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/entrar2.png"))); // NOI18N
        btnEntrar.setOpaque(true);
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 140, 50));

        Contraseña.setBackground(new java.awt.Color(34, 102, 145));
        Contraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Contraseña.setText("12345678");
        Contraseña.setBorder(null);
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 140, 30));

        txtCorreoElec.setBackground(new java.awt.Color(34, 102, 145));
        txtCorreoElec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCorreoElec.setText("caballero@hola.com");
        txtCorreoElec.setBorder(null);
        getContentPane().add(txtCorreoElec, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 122, 170, 40));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir2.png"))); // NOI18N
        btnSalir.setOpaque(true);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 137, 50));
        getContentPane().add(mtrContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 30, -1));

        lblCorreoElec.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblCorreoElec.setText("Correo Electronico:");
        getContentPane().add(lblCorreoElec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblContraseña.setText("Contraseña:");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        diseñoCorreoElec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usFem.png"))); // NOI18N
        diseñoCorreoElec.setText("jLabel5");
        getContentPane().add(diseñoCorreoElec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, 60));

        diseñoContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/contraseña.png"))); // NOI18N
        diseñoContraseña.setText("jLabel6");
        getContentPane().add(diseñoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 250, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Introduce tu Correo Electronico y tu Constraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 360, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FondoLOG.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 470, 380));

        barraRegistro.setOpaque(true);

        jMenu1.setText("Registrar");

        jmiRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Guardar.png"))); // NOI18N
        jmiRegistrar.setText("Registrar");
        jMenu1.add(jmiRegistrar);

        barraRegistro.add(jMenu1);

        setJMenuBar(barraRegistro);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPasswordField Contraseña;
    private javax.swing.JMenuBar barraRegistro;
    public javax.swing.JButton btnEntrar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel diseñoContraseña;
    private javax.swing.JLabel diseñoCorreoElec;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenuItem jmiRegistrar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreoElec;
    public javax.swing.JCheckBox mtrContraseña;
    public javax.swing.JTextField txtCorreoElec;
    // End of variables declaration//GEN-END:variables
}
